### ISSUE TITLE
 GKE: Error 403: The caller does not have permission, forbidden

### ISSUE THREAD

**Issue by ryepesg** [reactiveops/rbac-lookup#14]
Trying to run rbac-lookup with the `--gke` flag produces:
`Error loading RBAC Bindings: googleapi: Error 403: The caller does not have permission, forbidden`

The problem happens with multiples configurations of clusters:

```gcloud container clusters create --scopes compute-rw,storage-ro,gke-default c1

gcloud container clusters create --num-nodes=1 --disk-size=10Gi --machine-type=g1-small --scopes compute-rw,storage-ro,gke-default c1

gcloud container clusters update --enable-basic-auth c1

gcloud container clusters create --num-nodes=1 --disk-size=10Gi --machine-type=g1-small --node-version=1.12.5-gke.10 --cluster-version=1.12.5-gke.10 --scopes compute-rw,storage-ro,gke-default c1
```

The problem occurs even using a service account with the Owner role:

```
gcloud container clusters create --num-nodes=1 --disk-size=10Gi --machine-type=g1-small --service-account=$NODE_SA_EMAIL --node-version=1.12.5-gke.10 --cluster-version=1.12.5-gke.10 c1
```

**Comment by sudermanjr** [comment]
In GKE, owner does not grant full permissions inside the kubernetes cluster.  My guess is that you need to grant your user a clusterrolebinding with higher privileges. 

This stack overflow does a decent job of describing the process:
https://stackoverflow.com/questions/46307325/gke-clusterrolebinding-for-cluster-admin-fails-with-permission-error

**Comment by ryepesg** [comment]
Thank you @sudermanjr, but I get the same error even with the cluster-admin clusterrolebinding assigned to my user:

```
% kubectl describe clusterrolebindings cluster-admin-binding 
Name:         cluster-admin-binding
Labels:       <none>
Annotations:  <none>
Role:
  Kind:  ClusterRole
  Name:  cluster-admin
Subjects:
  Kind  Name                      Namespace
  ----  ----                      ---------
  User <MY_EMAIL>
```

**Comment by sudermanjr** [comment]
Ah, the issue is not the account used to start the cluster, it's the account you are using when you run rbac-lookup and the permissions that it has in your GCP account.  Basically, you need to be able to run some form of `gcloud iam ` command in your project.  I can dig further to find out exactly what's needed, but that's the direction to look

**Comment by ryepesg** [comment]
Thank you, but I am using the same account to create the cluster and also to run rbac-lookup (my user is the owner of the project and I am creating a cluster-admin role for it):

`gcloud container clusters create kube`

`kubectl create clusterrolebinding cluster-admin-binding --clusterrole cluster-admin --user $(gcloud config get-value account)`

`rbac-lookup --gke`
_Error loading RBAC Bindings: googleapi: Error 403: The caller does not have permission, forbidden_

**Comment by robscott** [comment]
Hey @ryepesg, thanks for reporting this problem! I think the confusion here is that you actually need GCP IAM access here, not just GCP cluster access. Even a GKE cluster admin might not actually have project IAM access.

There's 3 calls this could be happening on, to help me rule out one of them, can you try to run this command?

```
gcloud projects get-iam-policy YOUR_PROJECT_NAME_HERE
```

If that works for you, that rules out a problem with https://github.com/reactiveops/rbac-lookup/blob/master/lookup/lister.go#L198. On the other hand, if it doesn't you'll need more IAM access for your account.

Either way, there are a couple places above that in that method that could also trigger an error like that. I'll work on adding some better error handling so we can tell which of those actually triggered the error, as well as changing the initial scope request to be read only.

Thanks again for all the help debugging this!

**Comment by ryepesg** [comment]
Thank you @robscott, I am the owner of the project in IAM and I am also a cluster-admin of the cluster. Here is the output of the command:

```
% gcloud projects get-iam-policy $(gcloud config get-value project)
bindings:
- members:
  - group:<A_GROUP_EMAIL>
  role: projects/oauthz/roles/CustomRole
- members:
  - serviceAccount:kub-sa@oauthz.iam.gserviceaccount.com
  role: roles/compute.admin
- members:
  - serviceAccount:service-140183570641@compute-system.iam.gserviceaccount.com
  role: roles/compute.serviceAgent
- members:
  - user:<MY_EMAIL>
  role: roles/container.admin
- members:
  - serviceAccount:service-140183570641@container-engine-robot.iam.gserviceaccount.com
  role: roles/container.serviceAgent
- members:
  - serviceAccount:140183570641-compute@developer.gserviceaccount.com
  - serviceAccount:140183570641@cloudservices.gserviceaccount.com
  - serviceAccount:service-140183570641@containerregistry.iam.gserviceaccount.com
  role: roles/editor
- members:
  - serviceAccount:kub-sa@oauthz.iam.gserviceaccount.com
  role: roles/logging.logWriter
- members:
  - serviceAccount:kub-sa@oauthz.iam.gserviceaccount.com
  role: roles/monitoring.metricWriter
- members:
  - serviceAccount:kub-sa@oauthz.iam.gserviceaccount.com
  role: roles/monitoring.viewer
- members:
  - user:<MY_EMAIL>
  role: roles/owner
- members:
  - serviceAccount:kub-sa@oauthz.iam.gserviceaccount.com
  role: roles/storage.objectViewer
```

Thank you,
